config/routes.rb
Rails.application.routes.draw do
  get 'books/new'
  post 'books' => 'books#create'
  get 'books' => 'books#index' , as: 'index_book'
  get 'books/:id' => 'books#show' , as: 'book'
  get 'books/:id/edit' => 'books#edit' , as: 'edit_book'
  get '/top' => 'homes#top'
  root to: 'homes#top'
  patch 'books/:id' => 'books#update' , as: 'update_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  delete 'books/:id' => 'books#destroy' ,as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image

  validates :title, presence: true
  validates :body, presence: true
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def create
     @book = Book.new(book_params)
      if @book.save
       flash[:notice] = "Book was successfully created."     
       redirect_to book_path(@book.id)
      else
       @books = Book.all
       render :index
      end  
    end
    
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."    
    redirect_to book_path(@book.id)
   else 
   # flash.now[:alert] = "error" 
    render :edit
   end    
  end
  
   def destroy
    book =Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."  
    redirect_to '/books'
   end
   
   

  private

  def book_params
   params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
 <%= @book.errors.count %> errora prohibited this book from being saved:
 <ul>
  <% @book.errors.full_messages.each do |message| %>
   <li><%= message %></li>
  <% end %>
 </ul>
<% end %>

<h1>Editing Book</h1>
<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

 <h2>Title</h2>
 <%= f.text_field :title %>


 <h2>Boody</h2>
 <%= f.text_area :body %><br>

 <%= f.submit 'Update Book' %><br>
 <%= link_to "Show" , book_path(@book.id) %> |
 <%= link_to "Back", index_book_path %>

<% end %>

app/views/books/index.html.erb
<header>
 <h1>Books</h1>
</header>

<table>

 <tr>
  <th>Title</th>
  <th>Body</th>
 </tr>


    <% @books.each do |book| %>
   <tr>
     <td><%= book.title %></td>
     <td><%= book.body %></td>
      <td class="t-nav">
       <span class="book-show"> <%= link_to "Show" , book_path(book.id) %></span>
       <span class="book-edit"> <%= link_to "Edit" , edit_book_path(book.id) %></span>
       <span class="book-destroy"> <%= link_to "Destroy" , book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></span>
      </td>
    </tr>
     <% end %>

</table>



<h1>NewBook</h1>

<% if @book.errors.any? %>
 <%= @book.errors.count %> errora prohibited this book from being saved:
 <ul>
  <% @book.errors.full_messages.each do |message| %>
   <li><%= message %></li>
  <% end %>
 </ul>
<% end %>

 <%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_field :body %><br>

  <%= f.submit 'Create Book' %>

<% end %>

</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<p><strong>Title:</strong><%= @book.title %></p>

<p><strong>Body:</strong><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", index_book_path %>

app/views/homes/top.html.erb
<h1>ようこそ<strong>Bookers</strong>へ！</h1>
<p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や<br>

印象を共有し交換することができます</p>

<div class="start">
<%= link_to "start", index_book_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body
</html>